-- 코드를 입력하세요
SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS ADDRESS,
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS FORMATTED_PHONE_NUMBER
FROM USED_GOODS_USER JOIN USED_GOODS_BOARD
ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY USER_ID DESC